version: "3.9"

services:
  redis:
    container_name: my_redis
    image: "redislabs/redismod"  # redis/redistimeseries
    ports:
    - "15000:6379"
    # networks:
    # - pricer_network
    volumes:
    - ./redis:/data
    command: --dir /data --loadmodule /usr/lib/redis/modules/redistimeseries.so

#   pricer:
#     container_name: pricer
#     build: ./src/pricer
#     restart: always
#     ports:
#       - "8000:8000"
#     networks:
#     - pricer_network
#     depends_on:
#     - redis
#     env_file:
#     - ./src/.env

# networks:
#   pricer_network:
