version: "3.9"
# docker-compose up --scale queue=3 -d
services:
  redis:
    container_name: redis
    image: "redislabs/redismod"  # redis/redistimeseries
    ports:
      - "6379:6379"
    expose:
    - "6379"
    volumes:
      - ./redis:/data
    command: --dir /data --loadmodule /usr/lib/redis/modules/redistimeseries.so

  queue:
    build: ./src/queue
    restart: always
    depends_on:
    - redis
    env_file:
     - ./src/.env
    links:
    - redis

  pricer:
    container_name: pricer
    build: ./src/pricer
    restart: always
    ports:
      - "8000:8000"
    depends_on:
    - redis
    links:
    - redis
    env_file:
    - ./src/.env
    environment:
    - PYTHONUNBUFFERED=0
    - PYTHONPATH=/pricer

volumes:
  redis:
    driver: local

